### ISSUE TITLE
No browsers to run from create session

### ISSUE THREAD

**Issue by ilyinon** [wrike/callisto-chart#13]
Hello!

I've installed Callisto from this chart and can't create a new session manually. There isn't any browser.
<img width="1473" alt="image" src="https://github.com/wrike/callisto-chart/assets/4660057/21a906c0-c39f-4e74-a6b1-bc6e2e83df31">
Yet the config has
```
  browser:
    name: "chrome"
    chromeImage: "myregistry/vnc:chrome_119.0"
    firefoxImage: "myregistry/vnc:firefox_118.0"
    edgeImage: "myregistry/edge:119.0"
    firefoxWebdriverPath: "/wd/hub"  # because selenoid runs inside firefox container
```
   
Can you please advice how to fix this?
